Downgrade mongodb to fix ReferenceError
Error details:
os: options.runtimeAdapters?.os ?? require('os')

ReferenceError: require is not defined in ES module scope,
you can use import instead

This file is being treated as an ES module because it has a '.js' file
extension and '/usr/src/app/package.json' contains"type": "module".